### ISSUE TITLE
Fails to fetch entries

### ISSUE THREAD

**Issue by thokall** [tadeu95/BAGS#1]
Trying to download all entries from the genus Aglais using BAGS. The tool fetches no instances of Aglais io even though there is a bin (named BOLD:AAB4921) that contains a number of entries that is within my criteria (longer than 300bp and containing geo-info). Am I missing something or is this expected behaviour.

**Comment by pedroemanuelvieira** [comment]
Dear Thomas.
Thanks for raising this issue.
We were unaware of species with just two letters. We were removing genera and species names with one and two letters only. Now, we only kept the removal of names with one letter.
Thanks once again
